user nginx;

events {
    worker_connections 1000;
}

http {

    upstream userservice {
        server userservice:8080;
    }

    upstream authservice {
        server authservice:8080;
    }

    upstream classservice {
        server classservice:8080;
    }

    upstream bookingservice {
        server bookingservice:8080;
    }

    upstream adminservice {
        server adminservice:8080;
    }

    server {
        listen 4000;

        # Auth
        location /auth/ {
            proxy_pass http://authservice/;
        }

        # Users
        location /users/ {
            proxy_pass http://userservice/;
        }

        # Classes
        location /classes/ {
            proxy_pass http://classservice/;
        }

        # Bookings
        location /bookings/ {
            proxy_pass http://bookingservice/;
        }

        # Admin
        location /admin/ {
            proxy_pass http://adminservice/;
        }
    }
}