events {}

http {
    upstream userservice {
        server userservice:8080;
    }

    upstream classservice {
        server classservice:8080;
    }

    upstream bookingservice {
        server bookingservice:8080;
    }

    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://userservice/;
        }

        location /api/classes/ {
            proxy_pass http://classservice/;
        }

        location /api/bookings/ {
            proxy_pass http://bookingservice/;
        }
    }
}